name: Client Tests Workflow

# When this workflow is activated
on: 
  pull_request:

jobs:
  # Job 1: Preparation and cleanup
  prepare:
    name: Prepare Environment
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clean npm state and fix optional dependencies
        run: |
          rm -rf node_modules
          rm -rf package-lock.json
          cd ./app/frontend
          rm -rf node_modules
          rm -rf package-lock.json
          cd ../backend
          rm -rf node_modules
          rm -rf package-lock.json
          cd ../..
          npm cache clean --force

      - name: Install root dependencies
        run: npm install --force

      - name: Install frontend dependencies with rollup fix
        run: |
          cd ./app/frontend
          npm install --force
          # Explicitly install the missing rollup binary for linux
          npm install @rollup/rollup-linux-x64-gnu --save-dev --force || true

      - name: Install backend dependencies
        run: |
          cd ./app/backend
          npm install --force

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            app/frontend/node_modules
            app/backend/node_modules
          key: ${{ runner.os }}-npm-node20-${{ hashFiles('package-lock.json', 'app/frontend/package-lock.json', 'app/backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-node20-

  # Job 2: Frontend tests
  test-frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            app/frontend/node_modules
            app/backend/node_modules
          key: ${{ runner.os }}-npm-node20-${{ hashFiles('package-lock.json', 'app/frontend/package-lock.json', 'app/backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-node20-

      - name: Install dependencies if cache miss
        run: |
          if [ ! -d "node_modules" ]; then 
            npm install --force
          fi
          cd ./app/frontend
          if [ ! -d "node_modules" ]; then 
            npm install --force
            # Ensure rollup binary is available
            npm install @rollup/rollup-linux-x64-gnu --save-dev --force || true
          fi

      - name: Run frontend tests
        run: |
          cd ./app/frontend
          npm run test

  # Job 3: Backend tests
  test-backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    needs: prepare

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ask_and_trust
          POSTGRES_PASSWORD: SuperPassword!2025
          POSTGRES_DB: ask_and_trust_test
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready -U ask_and_trust -d ask_and_trust_test
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    env:
      NODE_ENV: testing
      DB_HOST: postgres
      DB_PORT: 5432 
      POSTGRES_USER: ask_and_trust
      POSTGRES_PASSWORD: SuperPassword!2025
      POSTGRES_DB: ask_and_trust_test
      ADMIN_EMAIL: admin@test.com
      ADMIN_PASSWORD: SuperSecret!2025
      ADMIN_FIRSTNAME: Admin
      ADMIN_LASTNAME: Test
      JWT_SECRET: supersecret

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            app/frontend/node_modules
            app/backend/node_modules
          key: ${{ runner.os }}-npm-node20-${{ hashFiles('package-lock.json', 'app/frontend/package-lock.json', 'app/backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-node20-

      - name: Install dependencies if cache miss
        run: |
          if [ ! -d "node_modules" ]; then 
            npm install --force
          fi
          cd ./app/backend
          if [ ! -d "node_modules" ]; then 
            npm install --force
          fi

      - name: Run backend tests
        run: |
          cd ./app/backend
          npm run test:postgresql
