name: Client Tests Workflow

# When this workflow is activated
on: 
  pull_request:

jobs:
  test-client:
    # Execution Environment
    runs-on: ubuntu-latest
    steps:
      # Clone the GitHub repository in GitHub Actions Virtual Machine
      # Make the files available by the workflow
      - name: Check out code
        uses: actions/checkout@v4

      - name: Clean npm state
        run: |
          rm -rf node_modules
          cd ./app/frontend
          rm -rf node_modules
          cd ../..
          npm cache clean --force

      - name: Install dependencies
        run: |
          cd ./app/frontend
          npm ci

      - name: Run tests
        run: |
          cd ./app/frontend
          npm test
