name: Docker Build Workflow

# When this workflow is activated
on:
  pull_request:
     branches:
       - main

jobs:
  docker-build:
  # Run if client test is a success
  # On build seulement l'image docker au merge sur main
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    # for existing actions, we need the keyword "uses"
    steps:
      # Clone the GitHub repository in GitHub Actions Virtual Machine
      # Make the files available by the workflow
      - name: Check out code
        uses: actions/checkout@v4

      # Enable to built multi-architectures images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Init Docker Buildx, a Docker Build extension
      # Allow parallel build, cache, etc. And build-push-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub with secrets stored in GitHub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push using docker-compose
      - name: Build and push with docker-compose
        run: |
          docker-compose build
          docker-compose push
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
