name: Docker Build Workflows

# When this workflow is activated
on:
# Run this workflow if test is completed
workflow_run:
  workflows: ["Client Tests Workflows"]
  types:
      - completed
pull_request:
    branches:
      - main

jobs:
  docker-build:
  # Run if client test is a success
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      #### for existing actions, we need the keyword "uses"

      # Clone the GitHub repository in GitHub Actions Virtual Machine
      # Make the files available by the workflow
      - name: Check out code
        uses: actions/checkout@v4

      # Enable to built multi-architectures images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Init Docker Buildx, a Docker Build extension
      # Allow parallel build, cache, etc. And build-push-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub with secrets stored in GitHub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker image anbd push it in DockerHub
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          # Indicate where is the app to build
          context: "{{defaultContext}}:client"
          # DockerHub user's name and app's name
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/AskAndTrust:latest
