name: Documentation Generation

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      # Retrieves source code from repository
     - uses: actions/checkout@v4

      # Configures the version of Node.js
     - name: Setup Node.js
       uses: actions/setup-node@v4
       with:
         node-version: '23'

      # Installe les dépendances
     - name: Install dependencies
       run: npm ci

      # Generates documentation
     - name: Generate Documentation
       run: npm run docs

      # Deploying documentation, for example to GitHub Pages
     - name: Deploy Documentation
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GIT_TOKEN_DOCS }}
         publish_dir: ./docs/build