name: Documentation Generation

on:
  pull_request:
    branches:
      - main

jobs:
  docs:
    # Run if client test is a success
    # Only build docker image when merging on main
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      # Retrieves source code from repository
     - uses: actions/checkout@v4

      # Configures the version of Node.js
     - name: Setup Node.js
       uses: actions/setup-node@v4
       with:
         node-version: '23'

      # Installs dependencies
     - name: Install dependencies
       run: npm ci

      # Generates documentation
     - name: Generate Documentation
       run: npm run docs

      # Deploying documentation, to GitHub Pages
     - name: Deploy Documentation
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GIT_TOKEN_DOCS }}
         publish_dir: ./docs/build